region: us
version: '2'
authtoken: 1c7XscplRzfsLy3Ziy4Eil0voxc_sUanTceuVwqemoqrdDuc
tunnels:
  twilio-app:
    addr: twilio-app:8001
    proto: http
  plivo-app:
    addr: plivo-app:8002
    proto: http
  bolna-app:
    addr: bolna-app:5001
    proto: http